spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/tourdb
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

